baseurl = "https://xsong.ltd/"
relativeurls = true

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

[languages.en]
  languageCode = "en-us"
  title = "Xiao Song"
  googleAnalytics = "UA-144652310-1"
  disqusShortname = "Xiao Song"
    # path to the favicon, under "static"
  favicon = "favicon.ico"


[languages.zh]
  languageCode = "zh-cn"

title = "宋骁"
author = "Xiao Song"
theme = "lithium"
googleAnalytics = "UA-144652310-1"
disqusShortname = "Xiao Song"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:slug/"

[[languages.zh.menu.main]]
    name = "首页"
    url = "/"
    weight = 1

[[languages.zh.menu.main]]
    name = "简历"
    url = "/zh/zhresume/"
    weight = 2

[[languages.zh.menu.main]]
    name = "文章"
    url = "/zh/post/"
    weight = 3
    
[[languages.zh.menu.main]]
    name = "Kaggle"
    url = "https://www.kaggle.com/rikdifos"
   weight = 4
  
[[languages.zh.menu.main]]
    name = "Github"
    url = "https://github.com/songxxiao"
   weight = 5
   
[[languages.zh.menu.main]]
  name = "English"
  url = "/en"
  weight = 6
  
[[languages.en.menu.main]]
    name = "Home"
    url = "/en"
    weight = 1

[[languages.en.menu.main]]
    name = "Vitae"
    url = "/en/enresume/"
   weight = 2

[[languages.en.menu.main]]
    name = "Posts"
    url = "/en/post/"
   weight = 3

[[languages.en.menu.main]]
    name = "Kaggle"
    url = "https://www.kaggle.com/rikdifos"
   weight = 4
  
[[languages.en.menu.main]]
    name = "Github"
    url = "https://github.com/songxxiao"
   weight = 5
   
[[languages.en.menu.main]]
  name = "中文"
  url = "/zh"
  weight = 6

[params]
    description = "Xiao Song's Website "
    footer = "&copy; [ ](https://xsong.ltd/)  "

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

