baseurl = "http://xsong.ltd/"
relativeurls = true
languageCode = "en-us"
title = "Xiao Song "
author = "Xiao Song"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "Xiao Song"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Resume"
    url = "/englishresume/"
   weight = 2
 
[[menu.main]]
    name = "Chinese Resume"
    url = "/chnresume/"
   weight = 3

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ECSTA7Y"
    weight = 4

[params]
    description = "Xiao Song's Website "
    footer = "&copy; [Xiao Song](https://hsiaosong.netlify.com/)  "

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

