baseurl = "/"
languageCode = "en-us"
title = "Xiao Song "
author = "Xiao Song"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]



[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
     name = "Xiao Song"
    url = "https://hsiaosong.netlify.com/2019/05/07/resume/"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ECSTA7Y"
[[menu.main]]
    name = "Resume"
    url = "https://hsiaosong.netlify.com/2019/05/07/resume/"

[params]
    description = "    "

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

