baseurl = "https://xsong.ltd/"
relativeurls = true

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

[languages.en]
  languageCode = "en-us"

[languages.zh]
  languageCode = "zh-cn"

title = "Xiao Song "
author = "Xiao Song"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "Xiao Song"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:slug/"

[[languages.zh.menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[languages.zh.menu.main]]
    name = "GitHub"
    url = "https://github.com/ECSTA7Y"
    weight = 2

[[languages.zh.menu.main]]
    name = "Resume"
    url = "/zhresume/"
    weight = 3

[[languages.zh.menu.main]]
    name = "Reward"
    url = "/reward/"
   weight = 4

[[languages.zh.menu.main]]
    name = 'Categories'
    url = "/tags/"
   weight = 5

[[languages.zh.menu.main]]
  name = "English"
  url = "../en"
  weight =6
  
[[languages.en.menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[languages.en.menu.main]]
    name = "Resume"
    url = "/enresume/"
   weight = 2
 
[[languages.en.menu.main]]
    name = "GitHub"
    url = "https://github.com/ECSTA7Y"
    weight = 3

[[languages.en.menu.main]]
    name = "Reward"
    url = "/reward/"
   weight = 4

[[languages.en.menu.main]]
    name = 'Categories'
    url = "/tags/"
   weight = 5

[[languages.en.menu.main]]
  name = "Chinese"
  url = "../zh"
  weight =6

[params]
    description = "Xiao Song's Website "
    footer = "&copy; [Xiao Song](https://xsong.ltd/)  "

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

