baseurl = "https://xsong.ltd/"
relativeurls = true

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

[languages.en]
  languageCode = "en-us"
  title = "Xiao Song"
  googleAnalytics = "UA-144652310-1"


[languages.zh]
  languageCode = "zh-cn"

title = "Xiao Song"
author = "Xiao Song"
theme = "hugo-lithium"
googleAnalytics = "UA-144652310-1"
disqusShortname = "Xiao Song"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:slug/"

[[languages.zh.menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[languages.zh.menu.main]]
    name = "Vitae"
    url = "/zh/zhresume/"
    weight = 2

[[languages.zh.menu.main]]
    name = "GitHub"
    url = "https://github.com/ECSTA7Y"
    weight = 3

[[languages.zh.menu.main]]
  name = "English"
  url = "/en"
  weight =4
  
[[languages.en.menu.main]]
    name = "Home"
    url = "/en"
    weight = 1

[[languages.en.menu.main]]
    name = "Vitae"
    url = "/en/enresume/"
   weight = 2
 
[[languages.en.menu.main]]
    name = "GitHub"
    url = "https://github.com/ECSTA7Y"
    weight = 3

[[languages.en.menu.main]]
  name = "Chinese"
  url = "/zh"
  weight =4

[params]
    description = "Xiao Song's Website "
    footer = "&copy; [ ](https://xsong.ltd/)  "

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

